### ISSUE TITLE
Error ENOENT

### ISSUE THREAD

**Issue by AM4Ryzen** [Yegorov/yadisk#8]
![ScreenShot_20200812224928](https://user-images.githubusercontent.com/39643236/90092315-1afd8f80-dd18-11ea-8cf4-b74fab8b730d.png)
Having this error when I try using the program. I have wget installed, and recently used it, so I don't know why yadisk doesn't recognize it

**Comment by Yegorov** [comment]
@asdf2345 thanks for report. It fixed in version 0.2.0
