### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by capriciousduck** [Yegorov/yadisk#9]
Unable to download this file: https://yadi.sk/i/0Vx6zbpPgHBRYA

Giving me this error

`Traceback (most recent call last):
        4: from /usr/local/bin/yadisk:23:in `<main>'
        3: from /usr/local/bin/yadisk:23:in `load'
        2: from /var/lib/gems/2.5.0/gems/yadisk-0.2.0/bin/yadisk:28:in `<top (required)>'
        1: from /var/lib/gems/2.5.0/gems/yadisk-0.2.0/lib/yadisk.rb:20:in `download'
/usr/lib/ruby/2.5.0/uri/common.rb:745:in `URI': bad argument (expected URI object or URI string) (ArgumentError)`

**Comment by Yegorov** [comment]
@capriciousduck Thanks for report!
You cannot download file because limit exceeded.

![screenshot](https://user-images.githubusercontent.com/2566462/96834186-3983b380-144a-11eb-83b5-3f3d6c0d027a.png)

I will try to release an update as soon as possible with the correct error message.

**Comment by capriciousduck** [comment]
Okay!
